[phases.setup]
# Ask Nixpacks to install Chromium and FFmpeg into the environment
packages = [
  "chromium",
  "ffmpeg",
  "libnss3",        # Puppeteer often needs libnss3 as well
  "libatk1.0-0",
  "libatk-bridge2.0-0",
  "libx11-xcb1",
  "libxcomposite1",
  "libxdamage1",
  "libxrandr2",
  "libgbm1",
  "libasound2",
  "libpangocairo-1.0-0",
  "libxss1",
  "libgtk-3-0",
  "libxshmfence1",
  "libglu1-mesa"
]
